name: "Release"

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
      - name: "Verify the release version"
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: true
          PACKAGE_DIR: ${{ github.workspace }}/custom_components/gsm_call
          PACKAGE_NAME: manifest.json
      - name: "Compress"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/gsm_call"
          zip -r "${{ runner.temp }}/gsm_call.zip" ./
      - name: "Publish"
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ runner.temp }}/gsm_call.zip
          body: >
            [![Downloads](https://img.shields.io/github/downloads/black-roland/homeassistant-gsm-call/${{ github.ref_name }}/total?style=flat-square)](https://github.com/black-roland/homeassistant-gsm-call/releases)
            [![Donate](https://img.shields.io/badge/%E2%98%95_Buy%20Me%20a%20Coffee-DALink-F57507?style=flat-square)](https://dalink.to/mansmarthome)
            [![Разовый донат](https://img.shields.io/badge/%E2%98%95_%D0%9E%D1%82%D0%B1%D0%BB%D0%B0%D0%B3%D0%BE%D0%B4%D0%B0%D1%80%D0%B8%D1%82%D1%8C-%D0%AEMoney-8A2BE2?style=flat-square)](https://mansmarthome.info/donate/?utm_source=github&utm_medium=referral&utm_campaign=gsm#%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D0%B0-%D0%B1%D1%8B%D1%81%D1%82%D1%80%D1%8B%D1%85-%D0%BF%D0%BB%D0%B0%D1%82%D0%B5%D0%B6%D0%B5%D0%B9)
          generate_release_notes: true
