name: "Release"

on:
  push:
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout"
        uses: "actions/checkout@v6"
      - name: "Verify the release version"
        uses: technote-space/package-version-check-action@v1
        with:
          COMMIT_DISABLED: true
          PACKAGE_DIR: ${{ github.workspace }}/custom_components/gsm_call
          PACKAGE_NAME: manifest.json
      - name: "Compress"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/gsm_call"
          zip -r "${{ runner.temp }}/gsm_call.zip" ./
      - name: "Publish"
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: ${{ runner.temp }}/gsm_call.zip
          body: >
            [![Downloads](https://img.shields.io/github/downloads/tbutiu/homeassistant-gsm-call/${{ github.ref_name }}/total?style=flat-square)](https://github.com/tbutiu/homeassistant-gsm-call/releases)
          generate_release_notes: true
